package stats

// NOTE: The structs in this package were generated by getting responses from ES, using
// this handy tool at https://mholt.github.io/json-to-go/ and making adjustments

type Tasks struct {
	Tasks map[string]Task `json:"tasks"`
}

type Task struct {
	Node   string `json:"node"`
	ID     int    `json:"id"`
	Type   string `json:"type"`
	Action string `json:"action"`
	Status struct {
		Phase string `json:"phase"`
	} `json:"status"`
	Description        string      `json:"description"`
	StartTimeInMillis  int64       `json:"start_time_in_millis"`
	RunningTimeInNanos int         `json:"running_time_in_nanos"`
	Cancellable        bool        `json:"cancellable"`
	ParentTaskID       string      `json:"parent_task_id"`
	Headers            interface{} `json:"headers"`
	Children           []Task      `json:"children"`
}
